---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-spring-boot-app
  template:
    metadata:
      labels:
        app: my-spring-boot-app
    spec:
      containers:
        - name: my-spring-boot-app
          image: dhillevajja/spc-march:1.0  # Replace with your actual image name
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/petclinic"  # Connect to MySQL service
            - name: SPRING_DATASOURCE_USERNAME
              value: "petclinic"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "petclinic"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-spring-boot-app
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30080  # This will expose the application on port 30080
  selector:
    app: my-spring-boot-app