apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: "mysql"
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.2
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "petclinic"
            - name: MYSQL_USER
              value: "petclinic"
            - name: MYSQL_PASSWORD
              value: "petclinic"
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      #volumeClaimTemplates:
      #  - metadata:
      #      name: mysql-persistent-storage
      #    spec:
      #      accessModes: [ "ReadWriteOnce" ]
      #      resources:
      #        requests:
      #          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      name: mysql
  selector:
    app: MySQL