
name: docker image build on git hub actions 

on:
    push: 
        branches:
            - dev

jobs:
    docker-build:
        runs-on: ubuntu-latest 

        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: docker image build
              run: |
                docker image build -t spc:${{ github.run_number }} .
                docker images ls
            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@0.28.0
              with:
                image-ref: spc:${{ github.run_number }}
                scan-type: image
                format: 'table'
                output: trivy.json





