
name: docker image build on git hub actions 

on:
    push: 
        branches:
            - dev

jobs:
    docker-build:
        runs-on: ubuntu-latest 

        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: docker image build
              run: |
                docker image build -t spc:${{ github.run_id }} .
                docker images ls
                docker container run -d -P spc:${{ github.run_id }}
                docker ps -a


